# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Import the recommended settings.
include: package:flutter_lints/flutter.yaml

# Apply mods atop the recommended settings.
#
# A list of all available lints and their documentation is published at
# https://dart-lang.github.io/linter/lints/index.html.
#
linter:
  rules:
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    sort_constructors_first: true
    avoid_print: false
    curly_braces_in_flow_control_structures: false
    no_runtimeType_toString: false
    only_throw_errors: true
    parameter_assignments: false
    require_trailing_commas: false
    use_key_in_widget_constructors: false