# For information on the generic Dart part of this file, see the following page:
# https://dart.dev/tools/pub/pubspec

name: splurge
description: Personal spending analysis

publish_to: 'none' # Remove this line if you wish to publish to pub.dev (why?)
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ##############################################################
  ### This is where I get to add my desired 3rd party libs@. ###

  auto_size_text: ^3.0.0
  flutter_riverpod: ^1.0.4
  fl_chart: ^0.55.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  desktop_window: ^0.4.0

  ##############################################################

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
